export const countries = [
  { label: "Worldwide / Global", value: "Worldwide" },
  { label: "Africa - General", value: "Africa" },
  { label: "South Africa", value: "South Africa" },
  { label: "Egypt", value: "Egypt" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Kenya", value: "Kenya" },
  { label: "USA", value: "USA" },
  { label: "Canada", value: "Canada" },
  { label: "United Kingdom", value: "UK" },
  { label: "European Union", value: "Europe" },
  { label: "Germany", value: "Germany" },
  { label: "France", value: "France" },
  { label: "Italy", value: "Italy" },
  { label: "Spain", value: "Spain" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Poland", value: "Poland" },
  { label: "Japan", value: "Japan" },
  { label: "China", value: "China" },
  { label: "South Korea", value: "South Korea" },
  { label: "India", value: "India" },
  { label: "ASEAN Region", value: "ASEAN" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Singapore", value: "Singapore" },
  { label: "Thailand", value: "Thailand" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Philippines", value: "Philippines" },
  { label: "Australia", value: "Australia" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Brazil", value: "Brazil" },
  { label: "Mexico", value: "Mexico" },
  { label: "Middle East", value: "Middle East" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "UAE", value: "UAE" },
  { label: "Turkey", value: "Turkey" },
  { label: "Russia", value: "Russia" },
];
